#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd
import numpy as np

#### Series

- it is a one dimensional array that can hold any data type. It is similar to a column in a spreadsheet or a database table. Each element in a Series has an associated index, which allows for easy access and manipulation of the data.

In [3]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(f"Series:\n{series}\n")
print(type(series))  # Output: <class 'pandas.core.series.Series'>

Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

<class 'pandas.core.series.Series'>

In [4]:
# create a Series with dictionary

data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(f"Series:\n{series_dict}\n")

Series:
a    1
b    2
c    3
dtype: int64

In [5]:
data  = [10,20,30]
index = ['a','b','c']
series_with_index = pd.Series(data,index= index)
print(f"Series with index:\n{series_with_index}\n")

Series with index:
a    10
b    20
c    30
dtype: int64

#### Data Frame

- A DataFrame in Pandas is a two-dimensional, labeled data structure that stores data in rows and columns, similar to a table in Excel.

In [6]:
# Data frame from dictionary of lists

data = {
    'Name': ['Krish','John','Jack'],
    'Age': [25, 30, 45],
    'City': ['Banglore', 'New York', 'Florida']
}

df =pd.DataFrame(data)
print(f"DataFrame:\n{df}\n")  
print(type(df))  # Output: <class 'pandas.core.frame.DataFrame'>

DataFrame:
    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

<class 'pandas.core.frame.DataFrame'>

In [7]:
# DAta frame from list of dictionaries

data = [
    {'Name': 'Krish', 'Age': 32, 'City': 'Banglore'},
    {'Name': 'John', 'Age': 34, 'City': 'Banglore'},
    {'Name': 'Jack', 'Age': 32, 'City': 'Banglore'},
    {'Name': 'Bappy', 'Age': 32, 'City': 'Banglore'},
]
df = pd.DataFrame(data)
print(f"DataFrame:\n{df}\n")

DataFrame:
    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2   Jack   32  Banglore
3  Bappy   32  Banglore

In [8]:
df =pd.read_csv("sales_data.csv")
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [9]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [10]:
# Accessing data from DataFrame
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [11]:
data = {
    'Name': ['Krish','John','Jack'],
    'Age': [25, 30, 45],
    'City': ['Banglore', 'New York', 'Florida']
}

df =pd.DataFrame(data)

In [12]:
df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [13]:
df['Name']  # Accessing a single column

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [14]:
type(df['Name'])  # Output: <class 'pandas.core.series.Series'>

pandas.core.series.Series

In [15]:
df.loc[0]  # Accessing a single row by index

Name       Krish
Age           25
City    Banglore
Name: 0, dtype: object

In [16]:
df.iloc[0][0]  # Accessing a single row by position

C:\Users\aksha\AppData\Local\Temp\ipykernel_22272\1311662183.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]  # Accessing a single row by position

'Krish'

In [17]:
# Accessing a specified element from DataFrame

df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [18]:
df.at[1, 'Name']  # Accessing a specified element by label

'John'

In [19]:
df.at[1, 'Age']

np.int64(30)

In [20]:
# Accessing a spiecified element using iat

df.iat[2,2]

'Florida'

In [21]:
# Data Manipulation with DataFrame

df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [22]:
df['Salary'] = [50000, 60000, 70000]  # Adding a new column
df

    Name  Age      City  Salary
0  Krish   25  Banglore   50000
1   John   30  New York   60000
2   Jack   45   Florida   70000

In Pandas, inplace is a parameter that determines whether a modification is applied directly to the original DataFrame or whether a new DataFrame is returned.
- inplace=True: Modifies the original DataFrame directly.
- inplace=False: Does not modify the original DataFrame directly; this is the default for many Pandas methods.

In [23]:
df.drop('Salary', axis=1, inplace=True)  # Dropping a column
df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [24]:
# Adding age to the columns of the DataFrame

df['Age'] += 1
df

    Name  Age      City
0  Krish   26  Banglore
1   John   31  New York
2   Jack   46   Florida

In [25]:
df.drop(0, axis=0, inplace=True)  # Dropping a row
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [26]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [27]:
# Displaying data types of each column in the DataFrame
print(f"Data types:\n{df.dtypes}")

# Displaying summary statistics of the DataFrame
print(f"\nSummary statistics:\n{df.describe()}")

Data types:
Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

Summary statistics:
       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [28]:
df.describe()  # Displaying summary statistics of the DataFrame

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000